name: Static StopWatch Deploy
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
    build:
        name: ssh into vm
        runs-on: ubuntu-latest
        steps:
        - name: use apple boy playbook actions
          uses: appleboy/ssh-action@v0.1.10
          with:
            host: ${{ secrets.Host }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.PRIVATE_KEY }}
            scripts: whoami
            

