name: Static StopWatch Deploy
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
    build:
        name: ssh into vm
        runs-on: ubuntu-latest
        steps:
        - name: use apple boy playbook actions to ssh VM
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_Host }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.PRIVATE_KEY }}
            port: ${{ secrets.PORT }}
            script: 
              whoami
              cd /home/ubuntu/app
            

